# Generated by Django 6.1.1 on 2026-09-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên kỳ thi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả kỳ thi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('order', models.IntegerField(default=1, verbose_name='Số thứ tự câu (Câu 1, Câu 2...)')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề đề thi / Mã đề')),
                ('duration', models.IntegerField(help_text='Thời gian làm bài tính bằng phút', verbose_name='Thời gian (phút)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255, verbose_name='Nội dung đáp án')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Là đáp án ĐÚNG')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Thuộc câu hỏi')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Thuộc đề thi'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Điểm số')),
                ('correct_answers', models.IntegerField(verbose_name='Số câu đúng')),
                ('total_questions', models.IntegerField(verbose_name='Tổng số câu')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp bài')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học sinh')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Đề thi')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn thi')),
                ('code', models.CharField(max_length=20, verbose_name='Mã môn học')),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='quiz.examperiod', verbose_name='Thuộc kỳ thi')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quiz.subject', verbose_name='Thuộc môn thi'),
        ),
    ]
