# Generated by Django 6.1.1 on 2026-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankchoice',
            name='exact_numeric_answer',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='exact_numeric_answer',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Đáp án Số thực (Dành riêng cho câu hỏi Số)'),
        ),
        migrations.AlterField(
            model_name='bankchoice',
            name='choice_text',
            field=models.TextField(verbose_name='Nội dung phương án lựa chọn (Hỗ trợ mã LaTeX)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Công khai (Học sinh được luyện tập)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=models.TextField(verbose_name='Nội dung câu hỏi (Hỗ trợ mã LaTeX)'),
        ),
    ]
