# Generated by Django 6.1.1 on 2026-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_bankchoice_exact_numeric_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Hình ảnh đính kèm câu hỏi'),
        ),
    ]
