# Generated by Django 6.1.1 on 2026-09-19 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questionbank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hạn nộp bài'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã bài thi'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_numeric',
            field=models.FloatField(default=0.5, verbose_name='Điểm mỗi câu Trả lời số'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_single',
            field=models.FloatField(default=0.25, verbose_name='Điểm mỗi câu Trắc nghiệm'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_tf',
            field=models.FloatField(default=1.0, verbose_name='Điểm tối đa mỗi câu Đúng/Sai'),
        ),
        migrations.CreateModel(
            name='ExamMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('NB', 'Nhận biết'), ('TH', 'Thông hiểu'), ('VD', 'Vận dụng'), ('VDC', 'Vận dụng cao')], max_length=5, verbose_name='Mức độ khó')),
                ('question_type', models.CharField(choices=[('SINGLE', 'Trắc nghiệm 1 đáp án đúng (4 lựa chọn)'), ('TF', 'Trắc nghiệm Đúng/Sai (Mỗi ý chọn Đúng hoặc Sai)'), ('NUMERIC', 'Trả lời ngắn dạng Số Thực')], max_length=10, verbose_name='Loại câu hỏi')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng câu')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_entries', to='quiz.quiz')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.topic', verbose_name='Chủ đề')),
            ],
            options={
                'verbose_name': 'Ma trận đề thi',
                'verbose_name_plural': 'Ma trận đề thi',
            },
        ),
    ]
