# Generated by Django 6.1.1 on 2026-09-19 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_deadline_quiz_exam_code_quiz_score_numeric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMatrixTopicSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Đặc tả chủ đề kiến thức')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_specs', to='quiz.quiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic', verbose_name='Chủ đề')),
            ],
            options={
                'verbose_name': 'Đặc tả chủ đề',
                'verbose_name_plural': 'Đặc tả chủ đề',
                'unique_together': {('quiz', 'topic')},
            },
        ),
    ]
