# Generated by Django 6.1.1 on 2026-09-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Kết quả làm bài', 'verbose_name_plural': 'Kết quả làm bài'},
        ),
        migrations.AddField(
            model_name='examresult',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Họ tên thí sinh'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số câu đúng'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Thời gian làm bài (giây)'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng số câu'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp bài'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Bài thi'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
    ]
