# Generated by Django 6.1.1 on 2026-09-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_examresult_options_examresult_candidate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu mở thi'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='exam_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã bài thi (6 chữ số)'),
        ),
    ]
