# Generated by Django 6.1.1 on 2026-09-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_start_time_alter_quiz_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='candidate_avatar',
            field=models.CharField(blank=True, default='avatar-1', max_length=50, verbose_name='Ảnh đại diện thí sinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='avatar-1', max_length=50, verbose_name='Ảnh đại diện'),
        ),
    ]
