# Generated by Django 6.1.1 on 2026-09-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_examresult_candidate_avatar_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingExamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='101', max_length=20, verbose_name='Mã đề thi (VD: 101, 102...)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tên bộ đề / Tiêu đề đáp án')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_keys', to='quiz.subject', verbose_name='Môn thi')),
            ],
            options={
                'verbose_name': 'Bộ đáp án chấm thi',
                'verbose_name_plural': 'Bộ đáp án chấm thi',
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GradingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='Số báo danh / Mã thí sinh')),
                ('student_name', models.CharField(max_length=150, verbose_name='Họ và tên thí sinh')),
                ('student_class', models.CharField(blank=True, default='', max_length=50, verbose_name='Lớp / Phòng thi')),
                ('exam_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Mã đề thí sinh làm')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Tổng điểm đạt được')),
                ('max_score', models.FloatField(default=10.0, verbose_name='Điểm tối đa')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Số câu đúng tuyệt đối')),
                ('student_answers', models.JSONField(blank=True, default=dict, verbose_name='Đáp án thí sinh điền')),
                ('grading_details', models.JSONField(blank=True, default=list, verbose_name='Chi tiết chấm từng câu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chấm')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người chấm')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.gradingexamkey', verbose_name='Mã đề chấm')),
            ],
            options={
                'verbose_name': 'Kết quả bài chấm',
                'verbose_name_plural': 'Kết quả bài chấm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradingKeyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Số thứ tự câu')),
                ('question_type', models.CharField(choices=[('SINGLE', 'Trắc nghiệm 1 đáp án đúng (SingleChoose)'), ('TF', 'Trắc nghiệm Đúng/Sai (TrueFalse)'), ('NUMERIC', 'Điền số thực (Numeric - Tối đa 4 ký tự)')], default='SINGLE', max_length=20, verbose_name='Loại câu hỏi')),
                ('score_weight', models.FloatField(default=0.25, verbose_name='Điểm cho câu hỏi này')),
                ('correct_single', models.CharField(blank=True, max_length=5, null=True, verbose_name='Đáp án SingleChoose (A/B/C/D)')),
                ('correct_tf', models.JSONField(blank=True, default=dict, verbose_name='Đáp án Đúng/Sai 4 ý (a,b,c,d)')),
                ('correct_numeric', models.CharField(blank=True, max_length=4, null=True, verbose_name='Đáp án Số thực (Tối đa 4 ký tự)')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.gradingexamkey', verbose_name='Bộ đáp án')),
            ],
            options={
                'verbose_name': 'Đáp án câu hỏi chấm',
                'verbose_name_plural': 'Đáp án câu hỏi chấm',
                'ordering': ['question_number'],
                'unique_together': {('key', 'question_number')},
            },
        ),
    ]
