# Generated by Django 6.1.1 on 2026-09-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_gradingexamkey_gradingrecord_gradingkeyquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp học (VD: 12A1)')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Khối lớp (VD: 12)')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú / Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Danh sách Lớp học',
                'ordering': ['grade', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gradingexamkey',
            name='score_numeric',
            field=models.FloatField(default=0.5, verbose_name='Điểm mỗi câu Điền số thực'),
        ),
        migrations.AddField(
            model_name='gradingexamkey',
            name='score_single',
            field=models.FloatField(default=0.25, verbose_name='Điểm mỗi câu SingleChoose'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Số Báo Danh (SBD)')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên học sinh')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='quiz.studentclass', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Danh sách Học sinh (Master)',
                'ordering': ['student_class__name', 'student_id'],
            },
        ),
    ]
