# Generated by Django 6.1.1 on 2026-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_studentclass_gradingexamkey_score_numeric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='num_numeric',
            field=models.PositiveIntegerField(default=6, verbose_name='Số câu Numeric (Điền số thực)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='num_single',
            field=models.PositiveIntegerField(default=24, verbose_name='Số câu SingleChoose (Trắc nghiệm 4 lựa chọn)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='num_tf',
            field=models.PositiveIntegerField(default=4, verbose_name='Số câu TrueFalse (Trắc nghiệm Đúng/Sai)'),
        ),
    ]
