# Generated by Django 6.1.1 on 2026-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_subject_num_numeric_subject_num_single_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='max_score_numeric',
            field=models.FloatField(default=3.0, verbose_name='Điểm tối đa phần Điền số thực'),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_score_single',
            field=models.FloatField(default=6.0, verbose_name='Điểm tối đa phần SingleChoose'),
        ),
    ]
