# Generated by Django 6.1.1 on 2026-09-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_subject_max_score_numeric_subject_max_score_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='quiz.studentclass', verbose_name='Các lớp áp dụng chấm bài'),
        ),
        migrations.AddField(
            model_name='subject',
            name='score_per_numeric_val',
            field=models.FloatField(default=0.5, verbose_name='Điểm mỗi câu Điền số thực'),
        ),
        migrations.AddField(
            model_name='subject',
            name='score_per_single_val',
            field=models.FloatField(default=0.25, verbose_name='Điểm mỗi câu SingleChoose'),
        ),
        migrations.AddField(
            model_name='subject',
            name='score_per_tf_val',
            field=models.FloatField(default=1.0, verbose_name='Điểm tối đa mỗi câu TrueFalse'),
        ),
    ]
