# Generated by Django 6.1.1 on 2026-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_subject_assigned_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingrecord',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='grading_sheets/annotated/', verbose_name='Ảnh phiếu đã chấm (vẽ nhận diện)'),
        ),
        migrations.AddField(
            model_name='gradingrecord',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='grading_sheets/original/', verbose_name='Ảnh phiếu gốc'),
        ),
    ]
