# Generated by Django 6.1.1 on 2026-09-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_gradingrecord_annotated_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingrecord',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.gradingexamkey', verbose_name='Mã đề chấm'),
        ),
    ]
