# Generated by Django 6.1.1 on 2026-09-21 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_gradingrecord_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài toán')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('time_limit', models.FloatField(default=1.0, verbose_name='Giới hạn thời gian (giây)')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='Giới hạn bộ nhớ (MB)')),
                ('initial_code_cpp', models.TextField(blank=True, default='', verbose_name='Code mẫu C++')),
                ('initial_code_python', models.TextField(blank=True, default='', verbose_name='Code mẫu Python')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bài toán lập trình',
                'verbose_name_plural': 'Bài toán lập trình',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python')], max_length=50, verbose_name='Ngôn ngữ')),
                ('code', models.TextField(verbose_name='Nội dung code')),
                ('status', models.CharField(choices=[('Pending', 'Đang chờ chấm'), ('Accepted', 'Đúng (Accepted)'), ('Wrong Answer', 'Sai (Wrong Answer)'), ('Time Limit Exceeded', 'Quá thời gian (TLE)'), ('Compilation Error', 'Lỗi biên dịch (CE)'), ('Runtime Error', 'Lỗi thực thi (RE)')], default='Pending', max_length=50, verbose_name='Trạng thái')),
                ('score', models.FloatField(default=0.0, verbose_name='Điểm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh nộp')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.codingquestion', verbose_name='Bài toán')),
            ],
            options={
                'verbose_name': 'Bài nộp lập trình',
                'verbose_name_plural': 'Bài nộp lập trình',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='', verbose_name='Dữ liệu đầu vào')),
                ('expected_output', models.TextField(blank=True, default='', verbose_name='Kết quả đầu ra mong đợi')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Testcase ẩn')),
                ('points', models.FloatField(default=10.0, verbose_name='Điểm số')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='quiz.codingquestion')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': 'Test cases',
            },
        ),
    ]
