# Generated by Django 6.1.1 on 2026-09-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_codingquestion_codesubmission_testcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bình luận')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quiz.codingquestion', verbose_name='Bài toán')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Bình luận Luyện Code',
                'verbose_name_plural': 'Bình luận Luyện Code',
                'ordering': ['-created_at'],
            },
        ),
    ]
