# Generated by Django 6.1.1 on 2026-09-21 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_codingcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_questions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('manager', 'Quản lý'), ('coding_contributor', 'Cộng tác viên lập trình'), ('user', 'Người dùng bình thường')], default='user', max_length=20, verbose_name='Vai trò'),
        ),
    ]
