# Generated by Django 6.1.1 on 2026-09-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_codingquestion_created_by_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chủ đề')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Chủ đề lập trình',
                'verbose_name_plural': 'Chủ đề lập trình',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='difficulty',
            field=models.CharField(choices=[('Dễ', 'Dễ'), ('Trung bình', 'Trung bình'), ('Khó', 'Khó'), ('Rất khó', 'Rất khó')], default='Dễ', max_length=50, verbose_name='Mức độ khó'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='max_score',
            field=models.IntegerField(default=10, verbose_name='Điểm tối đa (100% testcase)'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.codingtopic', verbose_name='Chủ đề'),
        ),
    ]
