# Generated by Django 6.1.1 on 2026-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_codingtopic_codingquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='points',
            field=models.FloatField(default=0.1, verbose_name='Điểm số'),
        ),
    ]
