# Generated by Django 6.1.1 on 2026-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_testcase_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='past_exam',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thuộc đề thi (đã thi trực tiếp)'),
        ),
    ]
