# Generated by Django 6.1.1 on 2026-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_codingexam_codingquestion_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='solution_code_cpp',
            field=models.TextField(blank=True, default='', verbose_name='Code đáp án chuẩn C++'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='solution_code_python',
            field=models.TextField(blank=True, default='', verbose_name='Code đáp án chuẩn Python'),
        ),
    ]
