# Generated by Django 6.1.1 on 2026-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_codingquestion_solution_code_cpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị với người dùng'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Công khai ở Luyện Code'),
        ),
    ]
