# Generated by Django 6.1.1 on 2026-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_codingquestion_is_active_codingquestion_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexam',
            name='duration',
            field=models.IntegerField(default=0, help_text='Nhập 0 nếu không giới hạn', verbose_name='Thời gian làm bài (phút)'),
        ),
    ]
