# Generated by Django 6.1.1 on 2026-09-21 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_codingexam_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Tổng điểm')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.codingexam', verbose_name='Kỳ thi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Thí sinh')),
            ],
            options={
                'verbose_name': 'Lượt làm bài thi lập trình',
                'verbose_name_plural': 'Lượt làm bài thi lập trình',
                'ordering': ['-total_score', 'start_time'],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
