# Generated by Django 6.1.1 on 2026-09-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_codingexamattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingexam',
            name='exam_type',
            field=models.CharField(choices=[('free', 'Tự do'), ('registered', 'Có đăng ký & kiểm duyệt')], default='free', max_length=20, verbose_name='Loại kỳ thi'),
        ),
        migrations.CreateModel(
            name='CodingExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='quiz.codingexam', verbose_name='Kỳ thi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Thí sinh')),
            ],
            options={
                'verbose_name': 'Đăng ký kỳ thi lập trình',
                'verbose_name_plural': 'Đăng ký kỳ thi lập trình',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
