# Generated by Django 6.1.1 on 2026-09-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_codingexam_exam_type_codingexamregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Mã số'),
        ),
    ]
