# Generated by Django 6.1.1 on 2026-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_userprofile_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='Chi tiết testcases'),
        ),
    ]
