# Generated by Django 6.1.1 on 2026-09-23 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_codesubmission_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='quiz.questionbank', verbose_name='Thuộc nhóm câu hỏi (nếu có)'),
        ),
        migrations.AlterField(
            model_name='exammatrixentry',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Trắc nghiệm 1 đáp án đúng (4 lựa chọn)'), ('TF', 'Trắc nghiệm Đúng/Sai (Mỗi ý chọn Đúng hoặc Sai)'), ('NUMERIC', 'Trả lời ngắn dạng Số Thực'), ('GROUP', 'Câu hỏi nhóm (Chỉ chứa nội dung dẫn)')], max_length=10, verbose_name='Loại câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Trắc nghiệm 1 đáp án đúng (4 lựa chọn)'), ('TF', 'Trắc nghiệm Đúng/Sai (Mỗi ý chọn Đúng hoặc Sai)'), ('NUMERIC', 'Trả lời ngắn dạng Số Thực'), ('GROUP', 'Câu hỏi nhóm (Chỉ chứa nội dung dẫn)')], default='SINGLE', max_length=10, verbose_name='Loại câu hỏi'),
        ),
    ]
