# Generated by Django 6.1.1 on 2026-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_questionbank_parent_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='input_format',
            field=models.JSONField(blank=True, default=dict, verbose_name='Định dạng dữ liệu đầu vào'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='output_format',
            field=models.JSONField(blank=True, default=dict, verbose_name='Định dạng dữ liệu đầu ra'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, verbose_name='Danh sách Subtasks / Ràng buộc'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='max_score',
            field=models.FloatField(default=10.0, verbose_name='Điểm tối đa (100% testcase)'),
        ),
    ]
