# Generated by Django 6.1.1 on 2026-09-25 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_codingquestion_input_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathDocConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Tên tệp gốc')),
                ('file_type', models.CharField(default='Image', max_length=20, verbose_name='Loại tệp')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước tệp (bytes)')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='math_conversions/inputs/', verbose_name='Tệp đầu vào')),
                ('output_docx', models.FileField(blank=True, null=True, upload_to='math_conversions/outputs/', verbose_name='Tệp Word kết quả')),
                ('extracted_latex', models.TextField(blank=True, default='', verbose_name='Nội dung văn bản & LaTeX trích xuất')),
                ('status', models.CharField(choices=[('Pending', 'Đang chờ xử lý'), ('Processing', 'Đang chuyển đổi'), ('Completed', 'Hoàn thành'), ('Failed', 'Thất bại')], default='Pending', max_length=50, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Thông báo lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tất')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_conversions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử chuyển đổi tài liệu Toán',
                'verbose_name_plural': 'Lịch sử chuyển đổi tài liệu Toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
