# Generated by Django 6.1.1 on 2026-09-26 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_mathdocconversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên gói')),
                ('code', models.SlugField(unique=True, verbose_name='Mã định danh gói (slug)')),
                ('plan_type', models.CharField(choices=[('B2C', 'Người dùng cá nhân (Học sinh / Giáo viên)'), ('B2B', 'Triển khai Trường học / Doanh nghiệp')], default='B2C', max_length=10, verbose_name='Phân loại gói')),
                ('billing_cycle', models.CharField(choices=[('MONTH', 'Hàng tháng'), ('YEAR', 'Hàng năm'), ('LIFETIME', 'Trọn đời')], default='YEAR', max_length=10, verbose_name='Chu kỳ thanh toán')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Giá bán thực tế (VNĐ)')),
                ('original_price', models.PositiveIntegerField(default=0, verbose_name='Giá niêm yết gốc (VNĐ)')),
                ('badge_text', models.CharField(blank=True, default='', max_length=50, verbose_name='Huy hiệu hiển thị (VD: Phổ biến nhất)')),
                ('short_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, default='', verbose_name='Chi tiết gói')),
                ('features_list', models.JSONField(blank=True, default=list, verbose_name='Danh sách quyền lợi nổi bật')),
                ('limits', models.JSONField(blank=True, default=dict, verbose_name='Cấu hình hạn mức (Limits JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở bán')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Gói nổi bật (Highlight)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gói dịch vụ (Plan)',
                'verbose_name_plural': 'Quản lý Gói dịch vụ (Plans)',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SystemLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200, verbose_name='Tên trường / Đơn vị triển khai')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='Người đại diện')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Số điện thoại')),
                ('domain', models.CharField(max_length=150, unique=True, verbose_name='Tên miền được cấp phép (Domain)')),
                ('license_key', models.TextField(verbose_name='Khoá bản quyền mã hoá (License Key)')),
                ('tier', models.CharField(choices=[('STANDARD', 'Gói Trung Tâm (Dưới 500 học sinh)'), ('CAMPUS', 'Gói Trường Học (Dưới 2.500 học sinh)'), ('ENTERPRISE', 'Gói Sở GD / Toàn Tỉnh (Không giới hạn)')], default='STANDARD', max_length=20, verbose_name='Hạng bản quyền')),
                ('max_students', models.PositiveIntegerField(default=500, verbose_name='Số học sinh tối đa (0 = Không giới hạn)')),
                ('max_teachers', models.PositiveIntegerField(default=20, verbose_name='Số giáo viên tối đa (0 = Không giới hạn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('issued_at', models.DateTimeField(verbose_name='Ngày cấp')),
                ('expires_at', models.DateTimeField(verbose_name='Ngày hết hạn bản quyền')),
                ('brand_title', models.CharField(blank=True, default='', max_length=150, verbose_name='Tiêu đề thương hiệu riêng')),
                ('brand_logo_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL Logo trường')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bản quyền hệ thống B2B (System License)',
                'verbose_name_plural': 'Quản lý Bản quyền B2B (System Licenses)',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=64, unique=True, verbose_name='Mã đơn hàng / Giao dịch')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền (VNĐ)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã huỷ')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('VIETQR', 'VietQR (Quét mã ngân hàng)'), ('SEPAY', 'Cổng thanh toán SePay'), ('PAYOS', 'Cổng thanh toán PayOS'), ('VNPAY', 'Cổng VNPAY'), ('MOMO', 'Ví điện tử MoMo'), ('MANUAL', 'Kích hoạt thủ công')], default='VIETQR', max_length=20, verbose_name='Phương thức thanh toán')),
                ('transfer_content', models.CharField(blank=True, default='', max_length=100, verbose_name='Cú pháp chuyển khoản')),
                ('gateway_transaction_id', models.CharField(blank=True, default='', max_length=150, verbose_name='Mã GD phía cổng thanh toán')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Phản hồi Webhook JSON')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thanh toán thành công')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.plan', verbose_name='Gói chọn mua')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Lịch sử giao dịch thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Đã hết hạn'), ('CANCELLED', 'Đã huỷ'), ('TRIAL', 'Dùng thử')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateTimeField(verbose_name='Ngày kích hoạt')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn (để trống = trọn đời)')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Tự động gia hạn')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú quản trị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='quiz.plan', verbose_name='Gói đang dùng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đăng ký của người dùng (Subscription)',
                'verbose_name_plural': 'Danh sách Đăng ký người dùng (Subscriptions)',
            },
        ),
    ]
