# Generated by Django 6.1.1 on 2026-09-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_plan_systemlicense_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='ProEdu - Hệ Thống Khảo Thí & Luyện Lập Trình', max_length=200, verbose_name='Tên hệ thống / Website')),
                ('site_slogan', models.CharField(default='Nền tảng thi trực tuyến, luyện code và chuyển đổi tài liệu AI', max_length=255, verbose_name='Khẩu hiệu (Slogan)')),
                ('hotline', models.CharField(default='0987.654.321', max_length=50, verbose_name='Hotline liên hệ')),
                ('contact_email', models.EmailField(default='contact@proedu.vn', max_length=254, verbose_name='Email hỗ trợ')),
                ('bank_id', models.CharField(default='MB', max_length=20, verbose_name='Mã ngân hàng (VietQR)')),
                ('bank_account_number', models.CharField(default='0987654321', max_length=50, verbose_name='Số tài khoản ngân hàng')),
                ('bank_account_name', models.CharField(default='PROEDU VIETNAM', max_length=150, verbose_name='Tên chủ tài khoản')),
                ('payment_prefix', models.CharField(default='PROEDU', max_length=20, verbose_name='Cú pháp nạp tiền (Prefix)')),
                ('enable_registration', models.BooleanField(default=True, verbose_name='Cho phép đăng ký tài khoản mới')),
                ('enable_vietqr', models.BooleanField(default=True, verbose_name='Bật thanh toán tự động VietQR')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Chế độ bảo trì hệ thống')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
            },
        ),
    ]
