# Generated by Django 6.1.1 on 2026-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Gemini API Key'),
        ),
    ]
