# Generated by Django 6.1.1 on 2026-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_systemsetting_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlicense',
            name='brand_banner_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL Banner trường'),
        ),
        migrations.AddField(
            model_name='systemlicense',
            name='brand_slogan',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Khẩu hiệu riêng'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='brand_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon trình duyệt (Upload file .ico/.png)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='brand_favicon_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hoặc Link URL Favicon'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo thương hiệu (Upload file)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='brand_logo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hoặc Link URL ảnh Logo'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2026 ProEdu - Hệ Thống Khảo Thí & Luyện Lập Trình. All rights reserved.', max_length=255, verbose_name='Bản quyền chân trang (Footer)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hero_banner',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Ảnh Banner trang chủ (Upload)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hero_banner_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hoặc Link URL ảnh Banner'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Nền tảng thi trắc nghiệm trực tuyến chuẩn hóa, hỗ trợ câu hỏi toán học MathJax/LaTeX, đồng hồ đếm ngược thông minh và chấm điểm tức thì.', verbose_name='Đoạn văn mô tả Banner'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hero_title',
            field=models.CharField(blank=True, default='Hệ Thống Khảo Thí Thông Minh', max_length=255, verbose_name='Tiêu đề Banner chính'),
        ),
        migrations.AlterField(
            model_name='systemlicense',
            name='brand_logo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL Logo trường'),
        ),
    ]
