# Generated by Django 6.1.1 on 2026-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_systemlicense_brand_banner_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='code',
            field=models.CharField(blank=True, help_text='Mã định danh duy nhất (VD: SO_SIEU_NT, BAI_01). Để trống sẽ tự sinh theo tên bài.', max_length=50, null=True, unique=True, verbose_name='Mã bài toán (Code)'),
        ),
    ]
