# Generated by Django 6.1.1 on 2026-09-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_codingquestion_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên lớp học')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Mã lớp tham gia (VD: lop-hoc/{code})')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Lời dặn của giáo viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('allow_join', models.BooleanField(default=True, verbose_name='Cho phép học sinh xin vào qua link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_coding_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên phụ trách')),
            ],
            options={
                'verbose_name': 'Lớp học Luyện Code',
                'verbose_name_plural': 'Lớp học Luyện Code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingClassroomTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhóm kiến thức (VD: Vòng lặp For/While, Mảng 1D...)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Yêu cầu cần đạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_topics', to='quiz.codingclassroom', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Nhóm kiến thức lớp học',
                'verbose_name_plural': 'Nhóm kiến thức lớp học',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ giáo viên duyệt'), ('approved', 'Chính thức'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('role', models.CharField(choices=[('student', 'Học sinh'), ('assistant', 'Trợ giảng')], default='student', max_length=20, verbose_name='Vai trò')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian yêu cầu')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='quiz.codingclassroom', verbose_name='Lớp học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_classroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Thành viên Lớp học Luyện Code',
                'verbose_name_plural': 'Thành viên Lớp học Luyện Code',
                'ordering': ['-joined_at'],
                'unique_together': {('classroom', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CodingClassroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự bài')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào lớp')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.codingclassroom', verbose_name='Lớp học')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='quiz.codingquestion', verbose_name='Bài toán lập trình')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='quiz.codingclassroomtopic', verbose_name='Nhóm kiến thức')),
            ],
            options={
                'verbose_name': 'Bài tập trong lớp',
                'verbose_name_plural': 'Bài tập trong lớp',
                'ordering': ['order', 'id'],
                'unique_together': {('classroom', 'question')},
            },
        ),
    ]
