# Generated by Django 6.1.1 on 2026-09-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_codingclassroom_codingclassroomtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_sample',
            field=models.BooleanField(default=False, verbose_name='Hiển thị công khai trên đề bài'),
        ),
    ]
